### ISSUE TITLE
jobs keep failing

### ISSUE THREAD

**Issue by RaYm0ndCheun9** [laymonage/spotify-to-github#1]
after setting up following README, actions keep failing, logs below:
```
[2024-01-25T04:43:36.173Z]: Getting all saved tracks…
/home/runner/work/actionspotify/actionspotify/src/spotify.ts:216
      return [...items, ...rest];
                    ^
TypeError: items is not iterable
    at Object.getAllSaved (/home/runner/work/actionspotify/actionspotify/src/spotify.ts:216:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.getAllSavedTracks (/home/runner/work/actionspotify/actionspotify/src/spotify.ts:279:15)
    at async main (/home/runner/work/actionspotify/actionspotify/src/main.ts:35:18)
Error: Process completed with exit code 1.
```

**Comment by laymonage** [comment]
Your token is probably not valid. You need a refresh token, not the access token which expires after 1 hour.

**Comment by RaYm0ndCheun9** [comment]
i regenerate refresh token with  [generator](https://spotify-refresh-token-generator.netlify.app/) and it still get error:
```
[2024-01-25T06:59:54.955Z]: Adding 4352 tracks to saved tracks playlist…
/home/runner/work/actionspotify/actionspotify/src/main.ts:218
  log(`Writing saved tracks playlist to ${savedTracksPlaylistFull!.id}.json…`);
                                                                   ^
TypeError: Cannot read properties of undefined (reading 'id')
    at main (/home/runner/work/actionspotify/actionspotify/src/main.ts:218:68)
Error: Process completed with exit code 1.
```

**Comment by laymonage** [comment]
Try increasing the delay, that looks like a rate limit issue.

**Comment by RaYm0ndCheun9** [comment]
increased to 1500ms but still dont fix this

then i disable the saved tracks related code and the problem solved

it might be a rate limit issue

**Comment by laymonage** [comment]
Yeah I think the saved tracks function don't have a delay in between the paginated requests. Try adding `sleep(1500)` inside this for loop:

https://github.com/laymonage/spotify-to-github/blob/3d5cab7831b0d47650cf1e3306c9c66879ae6921/src/spotify.ts#L208-L212

**Comment by RaYm0ndCheun9** [comment]
still don't fix this

I think it's because I have over 4000 saved tracks so rate limit stop me to read the mirror playlist
